    <nav>
        <div class="clogo">
            <img id="clogo" src="https://d1csarkz8obe9u.cloudfront.net/posterpreviews/business-logo-design-template-78655edda18bc1196ab28760f1535baa_screen.jpg?ts=1617645324" alt="Company logo">
            <h1>PXZ Institute</h1>
        </div>
    
    <div class="menu">   
    <ul class="navbar">
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply Now</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="enhancements2.php">Enhancements 2</a></li>
        <li><a href="phpenhancements.html">PHP Enhancements</a></li>
        <li><a href="manage.php">Manager's View</a></li>



    
    </ul> 
    </div>
    </nav>
